import { Activity, CheckCircle2, ChevronRight, GitBranch, RefreshCw, ShieldAlert, SlidersHorizontal, UserPlus, X } from "lucide-react";
import { useState } from "react";
import { ApiError } from "../api/client";
import { calibrationRequests, type CalibrationCandidateView, type CalibrationVersion } from "../api/calibration";
import { Card, EmptyState, ErrorState, LoadingState, SectionHeader, StatusBadge } from "../components/ui";
import { useCalibrationGovernance } from "../hooks/useCalibrationGovernance";
import { useLiveRefresh } from "../live/useLiveRefresh";
import { AdminUsersPanel } from "./AdminUsersPanel";
import { LiveDiagnosticsPanel } from "./LiveDiagnosticsPanel";
import { useEscapeDismiss } from "../hooks/useEscapeDismiss";

const formatTime = (value: string | null | undefined) => value ? new Date(value).toLocaleString() : "Unavailable";
const tone = (status: string): "success" | "warning" | "danger" | "neutral" => ["approved", "active", "passed"].includes(status) ? "success" : ["failed", "blocked"].includes(status) ? "danger" : status === "not_evaluated" ? "neutral" : "warning";
const weights = ["s", "t", "v", "h"] as const;

export function AdminCalibrationPage() {
  const state = useCalibrationGovernance();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [confirmation, setConfirmation] = useState<{ kind: "approve" | "activate" | "rollback"; id: string } | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);
  const [actionBusy, setActionBusy] = useState(false);
  const [section, setSection] = useState<"calibration" | "users" | "live">("calibration");
  useEscapeDismiss(confirmation !== null, () => setConfirmation(null));
  useLiveRefresh(["calibration_candidate", "calibration_validation", "calibration_version_approved", "calibration_version_activated", "calibration_version_rollback"], () => state.refresh(), true, "admin-calibration");
  const selected = state.candidates.find((item) => item.candidate.candidate_id === selectedId) ?? state.candidates[0] ?? null;
  const active = state.governance?.active_version ?? null;

  async function execute() {
    if (!confirmation) return;
    setActionBusy(true); setActionError(null);
    try {
      if (confirmation.kind === "approve") await calibrationRequests.approve(confirmation.id);
      if (confirmation.kind === "activate") await calibrationRequests.activate(confirmation.id);
      if (confirmation.kind === "rollback") await calibrationRequests.rollback(confirmation.id);
      setConfirmation(null); await state.refresh();
    } catch (caught) { setActionError(caught instanceof ApiError ? `${caught.status}: ${caught.message}` : "Governance action failed"); }
    finally { setActionBusy(false); }
  }

  if (state.loading && !state.governance) return <LoadingState label="Loading calibration governance" />;
  return <div className="admin-calibration-page"><div className="admin-tabs" role="tablist" aria-label="Administration sections"><button className={`admin-tab ${section === "calibration" ? "active" : ""}`} type="button" role="tab" aria-selected={section === "calibration"} onClick={() => setSection("calibration")}><SlidersHorizontal size={15} />Calibration Governance</button><button className={`admin-tab ${section === "users" ? "active" : ""}`} type="button" role="tab" aria-selected={section === "users"} onClick={() => setSection("users")}><UserPlus size={15} />Users & Access</button><button className={`admin-tab ${section === "live" ? "active" : ""}`} type="button" role="tab" aria-selected={section === "live"} onClick={() => setSection("live")}><Activity size={15} />Live Diagnostics</button></div>{section === "users" ? <AdminUsersPanel /> : section === "live" ? <LiveDiagnosticsPanel /> : <><div className="page-header"><div><p className="eyebrow">System Administrator</p><h2>Adaptive calibration governance</h2><p>Versioned review and approval of calibration candidates. Live fusion remains on source baseline weights.</p></div><div className="overview-refresh"><span>{state.lastRefreshedAt ? `Updated ${formatTime(state.lastRefreshedAt)}` : "Not refreshed yet"}</span><button className="button button-secondary" type="button" onClick={() => void state.refresh()} disabled={state.loading}><RefreshCw size={15} className={state.loading ? "spin" : undefined} />{state.loading ? "Refreshing" : "Refresh"}</button></div></div>
    {state.error ? <ErrorState body={state.error} /> : null}{actionError ? <div className="section-error" role="alert"><ShieldAlert size={15} />{actionError}</div> : null}
    <section className="overview-section"><SectionHeader title="Calibration status" description="Governance state only; no adaptive version is wired into Part 3 fusion." /><Card className="admin-status-card"><div className="admin-status-banner"><SlidersHorizontal size={20} /><div><strong>{active ? `Adaptive version ${active.version_number} is active in governance` : "No adaptive calibration version is active"}</strong><span>Part 3 live fusion integration: disabled. Source baseline remains authoritative.</span></div><StatusBadge tone={active ? "success" : "neutral"}>{active ? active.status : "baseline"}</StatusBadge></div>{state.governance?.reasons.map((reason) => <p className="risk-helper" key={reason}>{reason}</p>)}</Card></section>
    <section className="overview-section"><SectionHeader title="Current / baseline weights" description="Bounds 0.10–0.50 · required sum 1.00 · batch setting 0.02" />{active ? <WeightCard weights={active.weights} meta={`Version ${active.version_number} · approved ${formatTime(active.approved_at)} · activated ${formatTime(active.activated_at)}`} /> : <WeightCard weights={{ s: .30, t: .20, v: .35, h: .15 }} meta="Source baseline reference; no adaptive version is active" baseline />}</section>
    <section className="overview-section"><SectionHeader title="Candidate preview" description="Only immutable backend candidates are shown." />{state.candidates.length === 0 ? <Card><EmptyState title="No calibration candidates" body="No candidate index is available. Training is not exposed through this UI." /></Card> : <div className="admin-candidate-layout"><Card className="admin-candidate-list">{state.candidates.map((item) => <button className={`admin-candidate-row ${item.candidate.candidate_id === selected?.candidate.candidate_id ? "selected" : ""}`} key={item.candidate.candidate_id} type="button" onClick={() => setSelectedId(item.candidate.candidate_id)}><div><strong>{item.candidate.candidate_id}</strong><span>{formatTime(item.candidate.created_at)} · {item.candidate.status}</span></div><StatusBadge tone={tone(item.validation?.status ?? "not_evaluated")}>{item.validation?.status ?? "not_evaluated"}</StatusBadge><ChevronRight size={15} /></button>)}</Card>{selected ? <CandidateDetail item={selected} onApprove={() => setConfirmation({ kind: "approve", id: selected.candidate.candidate_id })} approveBusy={actionBusy} /> : null}</div>}</section>
    <section className="overview-section"><SectionHeader title="Immutable version history" description="Every approval, activation, and rollback remains visible." />{state.governance?.versions.length ? <Card className="admin-version-table"><div className="admin-version-head"><span>Version</span><span>Weights</span><span>Status</span><span>Source / audit</span><span>Created</span><span>Actions</span></div>{[...state.governance.versions].reverse().map((version) => <VersionRow key={version.version_id} version={version} active={active?.version_id === version.version_id} onActivate={() => setConfirmation({ kind: "activate", id: version.version_id })} onRollback={() => setConfirmation({ kind: "rollback", id: version.version_id })} />)}</Card> : <Card><EmptyState title="No calibration versions" body="No immutable approved or activated versions are available." /></Card>}</section>
    {confirmation ? <div className="modal-backdrop" role="presentation"><div className="decision-modal" role="dialog" aria-modal="true" aria-labelledby="calibration-confirm-title"><div className="modal-heading"><div><p className="eyebrow">Governance confirmation</p><h3 id="calibration-confirm-title">{confirmation.kind.toUpperCase()}</h3></div><button className="icon-button" type="button" aria-label="Close confirmation" onClick={() => setConfirmation(null)}><X size={17} /></button></div><p className="modal-context">This is an explicit immutable governance action. It does not automatically change Part 3 live fusion behavior.</p><div className="modal-actions"><button className="button button-quiet" type="button" onClick={() => setConfirmation(null)}>Cancel</button><button className="button button-primary" type="button" onClick={() => void execute()} disabled={actionBusy}>{actionBusy ? "Applying…" : `Confirm ${confirmation.kind}`}</button></div></div></div> : null}
  </>}</div>;
}

function WeightCard({ weights: value, meta, baseline = false }: { weights: { s: number; t: number; v: number; h: number }; meta: string; baseline?: boolean }) { return <Card className="admin-weight-card"><div className="admin-weight-meta"><span>{meta}</span><StatusBadge tone={baseline ? "neutral" : "success"}>{baseline ? "Reference" : "Active governance"}</StatusBadge></div>{["s", "t", "v", "h"].map((key) => <div className="admin-weight-row" key={key}><strong>{key.toUpperCase()}</strong><div className="admin-weight-track"><span style={{ width: `${value[key as keyof typeof value] * 100}%` }} /></div><span>{value[key as keyof typeof value].toFixed(2)}</span></div>)}<small>Minimum 0.10 · maximum 0.50 · total {Object.values(value).reduce((sum, item) => sum + item, 0).toFixed(2)}</small></Card>; }

function CandidateDetail({ item, onApprove, approveBusy }: { item: CalibrationCandidateView; onApprove: () => void; approveBusy: boolean }) { const candidate = item.candidate; const validation = item.validation; const eligible = candidate.projected_candidate_weights !== null && candidate.training_count === 30 && candidate.validation_count === 15 && validation?.passed === true; return <Card className="admin-candidate-detail"><div className="admin-detail-title"><div><span className="route-label">Candidate</span><h3>{candidate.candidate_id}</h3></div><StatusBadge tone={tone(validation?.status ?? candidate.status)}>{validation?.status ?? candidate.status}</StatusBadge></div><div className="admin-facts"><Fact label="Provider" value={candidate.provider_name ? `${candidate.provider_name} ${candidate.provider_version ?? ""}` : "Unavailable"} /><Fact label="Dataset identity" value={candidate.dataset_identity} /><Fact label="Training / validation" value={`${candidate.training_count} / ${candidate.validation_count} (required 30 / 15)`} /><Fact label="Batch gradient" value={candidate.batch_gradient_setting.toFixed(2)} /></div><div className="admin-comparison"><span>Weight</span><span>Baseline</span><span>Raw proposed</span><span>Projected</span>{weights.map((key) => <div className="admin-comparison-row" key={key}><strong>{key.toUpperCase()}</strong><span>{candidate.baseline_weights[key].toFixed(2)}</span><span>{candidate.raw_proposed_weights?.[key] === undefined ? "Unavailable" : candidate.raw_proposed_weights[key].toFixed(4)}</span><span>{candidate.projected_candidate_weights?.[key] === undefined ? "Unresolved" : candidate.projected_candidate_weights[key].toFixed(4)}</span></div>)}</div>{validation ? <div className="admin-validation"><strong>Validation: {validation.status}</strong><span>Policy: {validation.policy_name ?? "Unavailable"} · Evaluated {formatTime(validation.evaluated_at)}</span>{Object.entries(validation.metrics).map(([key, value]) => <span key={key}>{key}: {String(value)}</span>)}{validation.reasons.map((reason) => <small key={reason}>{reason}</small>)}</div> : <p className="risk-helper">Validation not evaluated.</p>}<div className="admin-detail-actions"><button className="button button-primary" type="button" onClick={onApprove} disabled={!eligible || approveBusy}>{eligible ? "Review approval" : "Approval unavailable"}</button></div></Card>; }

function VersionRow({ version, active, onActivate, onRollback }: { version: CalibrationVersion; active: boolean; onActivate: () => void; onRollback: () => void }) { return <div className="admin-version-row"><strong>v{version.version_number}</strong><span>S {version.weights.s.toFixed(2)} · T {version.weights.t.toFixed(2)} · V {version.weights.v.toFixed(2)} · H {version.weights.h.toFixed(2)}</span><StatusBadge tone={tone(version.status)}>{active ? "active" : version.status}</StatusBadge><span>{version.source_candidate_id ?? "No candidate"}{version.rollback_from_version ? ` · rollback from v${version.rollback_from_version}` : ""}</span><time>{formatTime(version.created_at)}</time><div>{version.status === "approved" ? <button className="button button-quiet" type="button" onClick={onActivate}>Activate</button> : null}{version.status === "approved" || version.status === "active" ? <button className="button button-quiet" type="button" onClick={onRollback}>Rollback</button> : null}</div></div>; }
function Fact({ label, value }: { label: string; value: string }) { return <div className="fact"><span>{label}</span><strong>{value}</strong></div>; }
