import { ChevronDown, ChevronRight, ExternalLink, Filter, RefreshCw, Search, ShieldCheck, X } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link } from "react-router-dom";
import { emptyEventFilters, type EventFilters, type EventRecord } from "../api/events";
import { Badge, Card, EmptyState, ErrorState, LoadingState, SectionHeader, StatusBadge } from "../components/ui";
import { useHistoryAudit } from "../hooks/useHistoryAudit";
import { useLiveRefresh } from "../live/useLiveRefresh";

const EVENT_TYPES = ["incident_decision", "operator_decision", "incident_evidence_retained", "sensor_reading", "vision_detection", "vision_road_evidence", "route_version", "traffic_command_invalidated", "actuator_command", "actuator_ack", "area_risk_calculated", "calibration_candidate", "calibration_validation", "calibration_version_approved", "calibration_version_activated", "calibration_version_rollback"];
const ENTITY_TYPES = ["incident", "route", "area", "calibration", "calibration_candidate", "sensor", "actuator"];
const groupFor = (type: string) => type.startsWith("incident_") ? "Incident / Decision" : type === "operator_decision" ? "Operator Feedback" : type.startsWith("sensor_") || type.startsWith("vision_") ? "Sensor / Perception" : type.startsWith("route_") || type === "traffic_command_invalidated" ? "Routing" : type.startsWith("actuator_") ? "Infrastructure / Actuator" : type.startsWith("area_risk") ? "Risk Intelligence" : type.startsWith("calibration_") ? "Calibration / Governance" : "Other";
const formatTime = (value: string) => new Date(value).toLocaleString();

export function HistoryAuditPage() {
  const audit = useHistoryAudit();
  const [draft, setDraft] = useState<EventFilters>(emptyEventFilters);
  const [expanded, setExpanded] = useState<number | null>(null);
  const [newActivity, setNewActivity] = useState(false);
  useLiveRefresh(EVENT_TYPES, () => { if (audit.skip === 0) { setNewActivity(false); return audit.refresh(); } setNewActivity(true); return undefined; }, true, "history");
  function submit(event: FormEvent) { event.preventDefault(); setNewActivity(false); audit.applyFilters(draft); }
  function clear() { setDraft(emptyEventFilters()); audit.clearFilters(); setNewActivity(false); }
  return <div className="history-page"><div className="page-header"><div><p className="eyebrow">Immutable audit history</p><h2>History / Audit</h2><p>Append-only Event-store records remain the source of truth.</p></div><div className="overview-refresh"><span>{audit.lastRefreshedAt ? `Updated ${formatTime(audit.lastRefreshedAt)}` : "Not refreshed yet"}</span><button className="button button-secondary" type="button" onClick={() => void audit.refresh()} disabled={audit.loading}><RefreshCw size={15} className={audit.loading ? "spin" : undefined} />{audit.loading ? "Refreshing" : "Refresh"}</button></div></div>
    <Card className="audit-filter-card"><SectionHeader title="Filter history" description="Queries are applied server-side against immutable Events." /><form className="audit-filters" onSubmit={submit}><label>Event type<select value={draft.eventType} onChange={(event) => setDraft({ ...draft, eventType: event.target.value })}><option value="">All event types</option>{EVENT_TYPES.map((type) => <option value={type} key={type}>{type} · {groupFor(type)}</option>)}</select></label><label>Entity type<select value={draft.entityType} onChange={(event) => setDraft({ ...draft, entityType: event.target.value })}><option value="">All entity types</option>{ENTITY_TYPES.map((type) => <option value={type} key={type}>{type}</option>)}</select></label><label>Entity ID<input value={draft.entityId} onChange={(event) => setDraft({ ...draft, entityId: event.target.value })} placeholder="Exact entity ID" /></label><label>From<input type="datetime-local" value={draft.startAt} onChange={(event) => setDraft({ ...draft, startAt: event.target.value })} /></label><label>To<input type="datetime-local" value={draft.endAt} onChange={(event) => setDraft({ ...draft, endAt: event.target.value })} /></label><div className="audit-filter-actions"><button className="button button-primary" type="submit"><Filter size={15} />Apply</button><button className="button button-quiet" type="button" onClick={clear}><X size={15} />Clear</button></div></form></Card>
    {newActivity ? <button className="audit-new-activity" type="button" onClick={() => { setNewActivity(false); void audit.refresh(); }}><Search size={15} />New activity available — refresh this page</button> : null}
    <section className="overview-section"><SectionHeader title="Audit records" description={`${audit.events.length} record(s) currently loaded; newest first`} />{audit.loading ? <LoadingState label="Loading immutable history" /> : audit.error ? <ErrorState body={audit.error} /> : audit.events.length === 0 ? <Card><EmptyState title="No matching audit records" body="No immutable events match the current filters." /></Card> : <Card className="audit-list-card"><div className="audit-list">{audit.events.map((record) => <AuditRecord key={record.id} record={record} expanded={expanded === record.id} onToggle={() => setExpanded(expanded === record.id ? null : record.id)} />)}</div>{audit.hasMore ? <div className="audit-load-more"><button className="button button-secondary" type="button" onClick={() => void audit.loadMore()} disabled={audit.loadingMore}>{audit.loadingMore ? "Loading…" : "Load more"}</button></div> : null}</Card>}</section>
    <p className="audit-immutability-note"><ShieldCheck size={14} />Records are append-only. This page provides read-only audit context; no history can be edited or deleted.</p>
  </div>;
}

function AuditRecord({ record, expanded, onToggle }: { record: EventRecord; expanded: boolean; onToggle: () => void }) { const operator = record.event_type === "operator_decision"; return <article className={`audit-record ${expanded ? "expanded" : ""}`}><button className="audit-record-summary" type="button" onClick={onToggle} aria-expanded={expanded}><span className="audit-expand">{expanded ? <ChevronDown size={16} /> : <ChevronRight size={16} />}</span><time dateTime={record.created_at}>{formatTime(record.created_at)}</time><div className="audit-event-title"><strong>{record.event_type}</strong><span>{groupFor(record.event_type)}</span></div><div className="audit-entity"><span>{record.entity_type}</span><strong>{record.entity_id}</strong></div><StatusBadge tone={operator ? "info" : "neutral"}>{operator ? "Verified feedback" : "Immutable"}</StatusBadge></button>{expanded ? <div className="audit-record-details"><div className="audit-detail-grid"><Fact label="Reason code" value={record.reason_code ?? "Unavailable"} /><Fact label="Human-readable reason" value={record.human_readable_reason ?? "Unavailable"} /><CrossLink record={record} /></div>{operator ? <OperatorEvidence payload={record.payload} /> : null}<details className="audit-raw"><summary>Technical payload</summary><pre>{JSON.stringify(record.payload, null, 2)}</pre></details></div> : null}</article>; }
function OperatorEvidence({ payload }: { payload: Record<string, unknown> }) { return <div className="audit-operator-evidence"><Badge tone="info">{String(payload.action ?? "Operator action")}</Badge><span>Actor {String(payload.operator_id ?? "Unavailable")} · {String(payload.operator_role ?? "Unavailable")}</span><strong>{String(payload.written_reason ?? "No written reason returned")}</strong><span>Incident {String(payload.incident_decision_id ?? "Unavailable")}</span></div>; }
function CrossLink({ record }: { record: EventRecord }) { if (record.entity_type === "incident") return <Fact label="Context" valueLink={`/incidents/${encodeURIComponent(record.entity_id)}`} value="Open incident" />; if (record.entity_type === "route") return <Fact label="Context" valueLink="/response" value="Open response view" />; if (record.entity_type === "calibration" || record.entity_type === "calibration_candidate") return <Fact label="Context" valueLink="/admin" value="Open governance" />; return <Fact label="Context" value="No linked view" />; }
function Fact({ label, value, valueLink }: { label: string; value: string; valueLink?: string }) { return <div className="fact"><span>{label}</span>{valueLink ? <Link to={valueLink}><strong>{value} <ExternalLink size={12} /></strong></Link> : <strong>{value}</strong>}</div>; }
