import { BrowserRouter, Link, Route, Routes } from "react-router-dom";
import type { ReactNode } from "react";

const evidence = [
  "Multimodal fire verification",
  "YOLOv8 detection and road-obstacle segmentation",
  "Severity assessment with life-safety person override",
  "Risk-aware A* routing with PRIMARY/STANDBY corridors",
  "Dual ESP32 SN1 + AC1 nodes over MQTT",
  "Operator, Firefighter, Planner, and Admin workflows",
];

const roles = {
  operator: {
    title: "Operator showcase",
    items: ["Annotated camera and evidence/fusion context", "Severity and route review", "Command and ACK visibility", "Confirm, Reject, Cancel, and response lifecycle controls"],
  },
  responder: {
    title: "Firefighter showcase",
    items: ["Current route, nodes, cost, and route version", "Blocked-edge and reroute explanation", "Traffic corridor state", "En Route, Arrived, and Resolved workflow"],
  },
  planner: {
    title: "Planner showcase",
    items: ["Area-risk factors and history", "Inspection queue and actions", "Risk ranking", "CSV export"],
  },
  admin: {
    title: "Admin showcase",
    items: ["System and device health", "Camera and AI health", "Calibration governance", "Approval, rollback, and audit surfaces"],
  },
} as const;

function ShowcaseNotice() {
  return <aside className="showcase-notice"><strong>Public Showcase Mode</strong><span>The live CityResponder prototype uses a local/hybrid runtime connected to physical ESP32 nodes, MQTT, and an overhead camera. This public deployment demonstrates the interface and verified project evidence.</span></aside>;
}

function Layout({ children }: { children: ReactNode }) {
  return <main className="showcase-page"><nav className="showcase-nav"><Link className="showcase-brand" to="/">CityResponder</Link><div><Link to="/operator">Operator</Link><Link to="/responder">Firefighter</Link><Link to="/planner">Planner</Link><Link to="/admin">Admin</Link><a href="https://github.com/jiahui-1101/CityResponder">GitHub</a></div></nav>{children}<footer className="showcase-footer">Recorded evidence and verified test results are labelled; no live hardware data is generated by this public build.</footer></main>;
}

function Home() {
  return <Layout><section className="showcase-hero"><p className="showcase-kicker">Understand → Respond → Learn</p><h1>CityResponder</h1><p className="showcase-lead">A tabletop urban emergency response platform connecting multimodal evidence, hazard-aware routing, physical traffic coordination, and role-based operations.</p><ShowcaseNotice /><div className="showcase-actions"><Link className="showcase-button" to="/operator">Open Public Showcase</Link><a className="showcase-button secondary" href="https://github.com/jiahui-1101/CityResponder">View GitHub Repository</a></div></section><section className="showcase-grid">{evidence.map((item) => <article className="showcase-card" key={item}><h2>{item}</h2><p>Verified in the local prototype or documented as a current evidence boundary.</p></article>)}</section><section className="showcase-results"><h2>Verified project evidence</h2><p>Traffic corridors PRIMARY, ALL_RED, and STANDBY were physically confirmed. The backend suite currently reports 35 passing tests; frontend typecheck, tests, and production build pass. WebSocket receipt → DOM proxy evidence is 3.1 ms average / 601 ms maximum.</p><p className="showcase-boundary">MQ-2 remains raw/provisional, servo/gate validation is deferred pending replacement, and strict backend-origin → DOM latency is unmeasured.</p></section></Layout>;
}

function RolePage({ role }: { role: keyof typeof roles }) {
  const content = roles[role];
  return <Layout><section className="showcase-role"><p className="showcase-kicker">Recorded Evidence · Public Showcase</p><h1>{content.title}</h1><ShowcaseNotice /><div className="showcase-card"><ul>{content.items.map((item) => <li key={item}>{item}</li>)}</ul></div><Link className="showcase-button" to="/">Back to overview</Link></section></Layout>;
}

export function PublicShowcaseApp() {
  const basename = import.meta.env.BASE_URL.replace(/\/$/, "") || undefined;
  return <BrowserRouter basename={basename}><Routes><Route path="/" element={<Home />} /><Route path="/operator" element={<RolePage role="operator" />} /><Route path="/responder" element={<RolePage role="responder" />} /><Route path="/planner" element={<RolePage role="planner" />} /><Route path="/admin" element={<RolePage role="admin" />} /><Route path="*" element={<Home />} /></Routes></BrowserRouter>;
}
