import { Download, Map, RefreshCw, ShieldAlert } from "lucide-react";
import { useEffect, useState } from "react";
import { Card, EmptyState, ErrorState, LoadingState, SectionHeader, StatusBadge } from "../components/ui";
import { useAreaRisk } from "../hooks/useAreaRisk";
import { useLiveRefresh } from "../live/useLiveRefresh";
import { inspectionRequests, type Inspection } from "../api/inspections";

const formatTime = (value: string | null | undefined) => value ? new Date(value).toLocaleString() : "Unavailable";
const tone = (status: string): "success" | "warning" | "neutral" => status === "calculated" ? "success" : status === "not_evaluated" ? "warning" : "neutral";

export function RiskPlannerPage() {
  const risk = useAreaRisk();
  useLiveRefresh(["area_risk_calculated"], () => risk.refresh(), true, "risk");
  const selected = risk.selected;
  const [inspections, setInspections] = useState<Inspection[]>([]);
  const [inspectionError, setInspectionError] = useState<string | null>(null);
  const [creating, setCreating] = useState(false);
  const loadInspections = async () => { try { setInspections(await inspectionRequests.list()); setInspectionError(null); } catch (caught) { setInspectionError(caught instanceof Error ? caught.message : "Unable to load inspection queue"); } };
  useEffect(() => { void loadInspections(); }, []);
  async function createInspection() { if (!selected) return; setCreating(true); try { await inspectionRequests.create({ area_id: selected.area_id, incident_id: null, reason: "Planner follow-up requested from risk factors", status: "OPEN", notes: null }); await loadInspections(); } catch (caught) { setInspectionError(caught instanceof Error ? caught.message : "Unable to create inspection"); } finally { setCreating(false); } }
  async function exportCsv() { const blob = await inspectionRequests.exportCsv(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "cityresponder-inspections.csv"; anchor.click(); URL.revokeObjectURL(url); }
  async function advanceInspection(item: Inspection) { const next = item.status === "OPEN" ? "IN_PROGRESS" : item.status === "IN_PROGRESS" ? "CLOSED" : "CLOSED"; if (next === item.status) return; try { await inspectionRequests.update(item.inspection_id, { status: next }); await loadInspections(); } catch (caught) { setInspectionError(caught instanceof Error ? caught.message : "Unable to update inspection"); } }
  return <div className="risk-page"><div className="page-header"><div><p className="eyebrow">City Risk Planner workspace</p><h2>Area risk intelligence</h2><p>Explainable read-only risk derived from operator-verified history.</p></div><div className="overview-refresh"><span>{risk.lastRefreshedAt ? `Updated ${formatTime(risk.lastRefreshedAt)}` : "Not refreshed yet"}</span><button className="button button-secondary" type="button" onClick={() => void risk.refresh()} disabled={risk.loading}><RefreshCw size={15} className={risk.loading ? "spin" : undefined} />{risk.loading ? "Refreshing" : "Refresh"}</button></div></div>
    {risk.error ? <ErrorState body={risk.error} /> : null}
    <section className="risk-overview-grid"><Card className="risk-stat"><span>Configured / persisted areas</span><strong>{risk.areas.length}</strong><small>No synthetic areas are created</small></Card><Card className="risk-stat"><span>Evaluation window</span><strong>180 days</strong><small>Area Risk only</small></Card><Card className="risk-stat"><span>Latest calculation</span><strong>{formatTime(risk.areas.reduce((latest, area) => !latest || area.calculated_at > latest ? area.calculated_at : latest, ""))}</strong><small>From immutable results</small></Card></section>
    <section className="overview-section"><SectionHeader title="Area risk overview" description="No geographic heatmap is shown without explicit area geometry." /><Card className="risk-map-placeholder"><Map size={22} /><div><strong>Area risk grid</strong><span>This is an area overview, not a geographic map. Spatial area geometry is not configured.</span></div></Card></section>
    <section className="overview-section"><SectionHeader title="Area risk list" description="Scores are never classified without source-defined boundaries." />{risk.loading ? <LoadingState label="Loading area risk" /> : risk.areas.length === 0 ? <Card><EmptyState title="No area risk calculated" body="No immutable area-risk results are available yet. Risk requires an explicit area identity and provider-backed F/R/E/A/M components." /></Card> : <Card className="risk-table-card"><div className="risk-table-head"><span>Area</span><span>Score</span><span>Status</span><span>Verified incidents</span><span>Calculated</span></div>{risk.areas.map((area) => <button className={`risk-table-row ${area.area_id === risk.selectedAreaId ? "selected" : ""}`} type="button" key={area.area_id} onClick={() => risk.selectArea(area.area_id)}><strong>{area.area_id}</strong><span>{area.score === null ? "Risk not calculated" : area.score.toFixed(2)}</span><StatusBadge tone={tone(area.status)}>{area.status}</StatusBadge><span>{area.verified_incident_count}</span><time>{formatTime(area.calculated_at)}</time></button>)}</Card>}</section>
    {selected ? <><section className="overview-section"><SectionHeader title={`Component breakdown · ${selected.area_id}`} description="Component definitions are configuration-dependent." /><Card className="risk-components"><div className="risk-component-head"><span>Component</span><span>Value</span><span>Fixed weight</span></div>{(["f", "r", "e", "a", "m"] as const).map((key) => <div className="risk-component-row" key={key}><strong>Component {key.toUpperCase()}</strong><span>{selected[key] === null ? "Unavailable" : selected[key]}</span><span>{(selected.weights[key.toUpperCase()] ?? 0).toFixed(2)}</span></div>)}{selected.score === null ? <div className="risk-note"><ShieldAlert size={15} />Risk not calculated — insufficient policy/data.</div> : null}<p className="risk-helper">F/R/E/A/M meanings and normalization are provider-defined; no defaults are applied.</p></Card></section><section className="overview-section"><SectionHeader title="Verified history" description={`${formatTime(selected.window_start)} → ${formatTime(selected.window_end)}`} /><Card className="risk-history"><p>{selected.verified_incident_count} eligible operator-verified incident reference(s) contributed to this result.</p>{selected.reasons.length ? <ul>{selected.reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul> : null}</Card></section><section className="overview-section"><SectionHeader title="Calculation history" description="Chronological immutable Area Risk snapshots for the selected area" />{risk.history.length ? <Card className="risk-history-list">{risk.history.map((item) => <div className="risk-history-row" key={`${item.area_id}-${item.calculated_at}`}><div><strong>{formatTime(item.calculated_at)}</strong><span>{item.status}</span></div><span>{item.score === null ? "Score unavailable" : `${item.score.toFixed(2)} / 100`}</span><span>{item.verified_incident_count} verified incident(s)</span></div>)}</Card> : <Card><EmptyState title="No calculation history" body="No immutable Area Risk snapshots exist for this area." /></Card>}</section></> : null}
    <section className="overview-section"><SectionHeader title="Inspection queue" description="Persisted planner follow-ups linked to area risk and incident context" action={<div className="decision-actions"><button className="button button-secondary" type="button" onClick={() => void exportCsv()}><Download size={14} />Export CSV</button><button className="button button-primary" type="button" disabled={!selected || creating} onClick={() => void createInspection()}>Create inspection</button></div>} />{inspectionError ? <div className="section-error" role="alert">{inspectionError}</div> : null}<Card className="risk-history-list">{inspections.length ? inspections.map((item) => <div className="risk-history-row" key={item.inspection_id}><div><strong>{item.area_id}</strong><span>{item.inspection_id}</span></div><span>{item.status}</span><span>{item.reason}</span>{item.status !== "CLOSED" ? <button className="button button-secondary" type="button" onClick={() => void advanceInspection(item)}>Advance</button> : <span>Closed</span>}</div>) : <EmptyState title="No inspections queued" body="Create a follow-up from a selected area after reviewing its factors." />}</Card></section>
  </div>;
}
